name: customizable_datetime_picker
description: Customizable Datetime Picker for Flutter projects. You can customize different parts of the picker like format locale divider color and many others.
version: 0.0.2
homepage: https://github.com/Nikolaiko/customizable-datetime-picker

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.widget.customizable_datetime_picker
        pluginClass: CustomizableDatetimePickerPlugin
      ios:
        pluginClass: CustomizableDatetimePickerPlugin
      macos:
        pluginClass: CustomizableDatetimePickerPlugin
