name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: Nikolaiko/customizable-datetime-picker/.github/workflows/publish.yml@main
    # with:
    #   working-directory: path/to/package/within/repository
